// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Retail.Infrastructure.Persistence;

#nullable disable

namespace Retail.Infrastructure.Migrations
{
    [DbContext(typeof(RetailDbContext))]
    partial class RetailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Retail.Domain.Pricing.ChannelPriceList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_list_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("Channel")
                        .HasDatabaseName("ix_channel_price_lists_channel");

                    b.HasIndex("Channel", "PriceListId")
                        .IsUnique()
                        .HasDatabaseName("ix_channel_price_lists_channel_list");

                    b.ToTable("channel_price_lists", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Pricing.CustomerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("customer_groups", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Pricing.CustomerGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_group_members_group_customer");

                    b.ToTable("customer_group_members", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Pricing.CustomerGroupPriceList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_list_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_customer_group_price_lists_group_id");

                    b.HasIndex("PriceListId")
                        .HasDatabaseName("ix_customer_group_price_lists_price_list_id");

                    b.ToTable("customer_group_price_lists", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Pricing.CustomerPriceList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_list_id");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_price_lists_customer_id");

                    b.HasIndex("CustomerId", "PriceListId")
                        .HasDatabaseName("ix_customer_price_lists_customer_list");

                    b.ToTable("customer_price_lists", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Pricing.OrderVolumeDiscount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount_percentage");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("max_discount_amount");

                    b.Property<decimal?>("MinOrderQuantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("min_order_quantity");

                    b.Property<decimal?>("MinOrderTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("min_order_total");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_list_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.HasKey("Id");

                    b.HasIndex("PriceListId", "IsActive", "Priority")
                        .HasDatabaseName("ix_order_volume_discounts_list_active_priority");

                    b.ToTable("order_volume_discounts", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Pricing.PriceList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("RoundingRule")
                        .HasColumnType("integer")
                        .HasColumnName("rounding_rule");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_price_lists_is_active");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_price_lists_priority");

                    b.ToTable("price_lists", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Pricing.PriceListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount_percentage");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("item_type");

                    b.Property<decimal?>("MaxQuantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("max_quantity");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("min_price");

                    b.Property<decimal>("MinQuantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("min_quantity");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price");

                    b.Property<bool>("PriceIncludesTax")
                        .HasColumnType("boolean")
                        .HasColumnName("price_includes_tax");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_list_id");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PriceListId", "ItemType", "ReferenceId")
                        .HasDatabaseName("ix_price_list_items_list_type_ref");

                    b.ToTable("price_list_items", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Pricing.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CanStackWithOthers")
                        .HasColumnType("boolean")
                        .HasColumnName("can_stack_with_others");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("coupon_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<int?>("MaxUsesPerCustomer")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses_per_customer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_count");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("CouponCode")
                        .IsUnique()
                        .HasDatabaseName("ix_promotions_coupon_code_unique")
                        .HasFilter("coupon_code IS NOT NULL");

                    b.HasIndex("IsActive", "ValidFrom", "ValidTo")
                        .HasDatabaseName("ix_promotions_is_active_valid_from_valid_to");

                    b.ToTable("promotions", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Pricing.PromotionAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<int?>("BuyQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("buy_quantity");

                    b.Property<Guid?>("BuyReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("buy_reference_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount_percentage");

                    b.Property<int?>("GetQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("get_quantity");

                    b.Property<Guid?>("GetReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("get_reference_id");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id");

                    b.Property<Guid?>("TargetReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_reference_id");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId")
                        .HasDatabaseName("ix_promotion_actions_promotion_id");

                    b.ToTable("promotion_actions", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Pricing.PromotionCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConditionType")
                        .HasColumnType("integer")
                        .HasColumnName("condition_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DecimalValue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("decimal_value");

                    b.Property<int?>("IntValue")
                        .HasColumnType("integer")
                        .HasColumnName("int_value");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId")
                        .HasDatabaseName("ix_promotion_conditions_promotion_id");

                    b.ToTable("promotion_conditions", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Pricing.PromotionUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("ExternalOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_order_id");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id");

                    b.Property<DateTimeOffset>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_promotion_usages_customer_id");

                    b.HasIndex("PromotionId")
                        .HasDatabaseName("ix_promotion_usages_promotion_id");

                    b.ToTable("promotion_usages", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Pricing.ScheduledPriceChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<decimal?>("NewDiscountPercentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("new_discount_percentage");

                    b.Property<decimal?>("NewMinPrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("new_min_price");

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("new_price");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_list_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PriceListId")
                        .HasDatabaseName("ix_scheduled_price_changes_price_list_id");

                    b.HasIndex("Status", "EffectiveAt")
                        .HasDatabaseName("ix_scheduled_price_changes_status_effective_at");

                    b.ToTable("scheduled_price_changes", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Sales.AppliedPromotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("discount_amount");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id");

                    b.Property<string>("PromotionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("promotion_name");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId")
                        .HasDatabaseName("ix_applied_promotions_quote_id");

                    b.ToTable("applied_promotions", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Sales.PaymentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<int>("Method")
                        .HasColumnType("integer")
                        .HasColumnName("method");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_payment_lines_invoice_id");

                    b.ToTable("payment_lines", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Sales.SaleInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uuid")
                        .HasColumnName("cashier_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ElectronicDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("electronic_document_id");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_number");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<bool>("RequiresElectronicInvoice")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_electronic_invoice");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("sale_invoices", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Sales.SaleQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("PromotionDiscountAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("promotion_discount_amount");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("quote_number");

                    b.Property<Guid>("SalesPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_person_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_until");

                    b.Property<decimal>("VolumeDiscountAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("volume_discount_amount");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sale_quotes_customer_id");

                    b.HasIndex("SalesPersonId")
                        .HasDatabaseName("ix_sale_quotes_sales_person_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sale_quotes_status");

                    b.HasIndex("ValidUntil")
                        .HasDatabaseName("ix_sale_quotes_valid_until");

                    b.ToTable("sale_quotes", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Sales.SaleQuoteLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount_percentage");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("line_total");

                    b.Property<string>("PriceListName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("price_list_name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("ResolutionSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resolution_source");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId")
                        .HasDatabaseName("ix_sale_quote_lines_quote_id");

                    b.ToTable("sale_quote_lines", (string)null);
                });

            modelBuilder.Entity("Retail.Infrastructure.Persistence.NumberSequence", b =>
                {
                    b.Property<string>("SequenceName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sequence_name");

                    b.Property<long>("CurrentValue")
                        .HasColumnType("bigint")
                        .HasColumnName("current_value");

                    b.HasKey("SequenceName");

                    b.ToTable("number_sequences", (string)null);
                });

            modelBuilder.Entity("Retail.Domain.Pricing.CustomerGroupMember", b =>
                {
                    b.HasOne("Retail.Domain.Pricing.CustomerGroup", null)
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Retail.Domain.Pricing.OrderVolumeDiscount", b =>
                {
                    b.HasOne("Retail.Domain.Pricing.PriceList", null)
                        .WithMany("OrderDiscounts")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Retail.Domain.Pricing.PriceListItem", b =>
                {
                    b.HasOne("Retail.Domain.Pricing.PriceList", null)
                        .WithMany("Items")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Retail.Domain.Pricing.PromotionAction", b =>
                {
                    b.HasOne("Retail.Domain.Pricing.Promotion", null)
                        .WithMany("Actions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Retail.Domain.Pricing.PromotionCondition", b =>
                {
                    b.HasOne("Retail.Domain.Pricing.Promotion", null)
                        .WithMany("Conditions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Retail.Domain.Pricing.PromotionUsage", b =>
                {
                    b.HasOne("Retail.Domain.Pricing.Promotion", null)
                        .WithMany("Usages")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Retail.Domain.Sales.AppliedPromotion", b =>
                {
                    b.HasOne("Retail.Domain.Sales.SaleQuote", null)
                        .WithMany("AppliedPromotions")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Retail.Domain.Sales.PaymentLine", b =>
                {
                    b.HasOne("Retail.Domain.Sales.SaleInvoice", null)
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Retail.Domain.Sales.SaleQuoteLine", b =>
                {
                    b.HasOne("Retail.Domain.Sales.SaleQuote", null)
                        .WithMany("Lines")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Retail.Domain.Pricing.CustomerGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Retail.Domain.Pricing.PriceList", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("OrderDiscounts");
                });

            modelBuilder.Entity("Retail.Domain.Pricing.Promotion", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Conditions");

                    b.Navigation("Usages");
                });

            modelBuilder.Entity("Retail.Domain.Sales.SaleInvoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Retail.Domain.Sales.SaleQuote", b =>
                {
                    b.Navigation("AppliedPromotions");

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
